### ISSUE TITLE
Simple discrete solver

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/SimpleDiffEq.jl#1]

**Comment by ChrisRackauckas** [comment]
@Datseris

**Comment by Datseris** [comment]
PR coming soon, just came home from work!

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/SimpleDiffEq.jl/commit/36e951c4495060b37e8092258c9ca71daa6be7a2
