### ISSUE TITLE
Hardcode qold, gamma,.... etc. besides atol/rtol ?

### ISSUE THREAD

**Issue by Datseris** [JuliaDiffEq/SimpleDiffEq.jl#11]
Hey, I am making the final steps necessary to make this usable in **DynamicalSystems.jl**: using some internal norm as an adjustable field and allowing `init` to also take keywords.

At the moment `__init` doesn't take any keywords, they are all hardcoded to the integrator. So why make them a field of the integrator and not constants instead? Or something similar as in the `rs`, we put them all in a vector?

But abstol/reltol should be made adjustable through init (this is what I am doing now). What do you thing about the `gamma, etc.` ?

**Comment by ChrisRackauckas** [comment]
> So why make them a field of the integrator and not constants instead?

Yeah, that's the right thing to do.
