### ISSUE TITLE
Simple Dopri

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/SimpleDiffEq.jl#3]

**Comment by ChrisRackauckas** [comment]
Possibly good starter code: 
https://github.com/JuliaDiffEq/DifferentialEquations.jl/blob/v0.5.0/src/ode/ode_integrators.jl#L1070-L1155

**Comment by Datseris** [comment]
Crosspost: https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/issues/76 

(notice, the bounty is not yet operational because setting up paypal is hard if you're not American)
