### ISSUE TITLE
Simple Vern9 ?

### ISSUE THREAD

**Issue by Datseris** [JuliaDiffEq/SimpleDiffEq.jl#5]
`ChaosTools` will make really good use of this. Reasons:

* We (will) use `step!` exclusively.
* Many algorithms I employ only work for continuous (and differentiable) vector field, making callbacks that change states or do crazy stuff not applicable. 
* Since we use only `step!`, callbacks for saving are also not applicable

**Comment by ChrisRackauckas** [comment]
Possibly good starter code: https://github.com/JuliaDiffEq/DifferentialEquations.jl/blob/v0.5.0/src/ode/ode_integrators.jl#L2179-L2234

**Comment by Datseris** [comment]
Crosspost: https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/issues/76 

(notice, the bounty is not yet operational because setting up paypal is hard if you're not American)

**Comment by Datseris** [comment]
I don't think this is really necessary anymore. SimpleATsit5 does the job.
